### ISSUE TITLE
Add cake-contrib user

### ISSUE THREAD

**Issue by gep13** [georgechang/Cake.Unicorn#3]
First of all, I wanted to thank you for adding to the Cake community by adding this addin.

I was just wondering if you had seen this blog post:

http://cakebuild.net/blog/2016/08/cake-contribution-organization

We are currently going through a process of increasing the visibility of addins, and also trying to ensure their long term maintainability.

To that end, we are asking addin creators to add the cake-contrib user on NuGet as a co-owner (this can be done through the NuGet website by clicking on Manage Owners on the package page).

Would you be interested in doing this? If you have any questions about this, please let me know. There was some initial concern that the Cake Team were trying to "take over" packages, and that couldn't be further from the truth, and if you have this concern, or others, I would like to address them.

Thanks!

**Comment by georgechang** [comment]
Done! Thanks for the blog post, it's very helpful. Happy to move it to the cake-contrib Github org as well.

**Comment by gep13** [comment]
@georgechang thank you for adding the cake-contrib user to the package.  If you want to start the process of moving this repository to you Cake Contrib Organisation, you can see some more information here:

https://github.com/cake-contrib/home#how-do-i-as-an-addin-author-transfer-a-repository-to-the-organisation

The first step is something that you would need to initiate, and from there, we can do the rest of the work.

**Comment by gep13** [comment]
@georgechang just wanted to follow up with this again, to see if moving this repo under the Cake-Contrib Organisation is something that you wanted to do.  Thanks
